config/routes.rb
Rails.application.routes.draw do

resources :tweets, only: [:index]

root "tweets#index"

get "/requestlimit", to: "tweets#too_many_requests", as: :too_many_requests

get "*path", to: redirect('/')

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :twitter_client

  



	def twitter_client

		Twitter::REST::Client.new do |config|
		  config.consumer_key        = ENV["TWITTER_CONSUMER_KEY"]
		  config.consumer_secret     = ENV["TWITTER_CONSUMER_SECRET"]
		  config.access_token        = ENV["TWITTER_ACCESS_TOKEN"]
		  config.access_token_secret = ENV["TWITTER_ACCESS_SECRET"]
		end

	end


  


  
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController


rescue_from Twitter::Error::TooManyRequests, with: :too_many_requests

	def index

	    if params[:search]

	      @tweets = twitter_client.search("#{params[:search]}+jobs+london").take(20).map {|t| t.id}

	      @tweet_id = Kaminari.paginate_array(@tweets).page(params[:page]).per(10)

	    else

	      @tweets = twitter_client.search("london jobs technology OR tech OR web").take(20).map {|t| t.id}

	      @tweet_id = Kaminari.paginate_array(@tweets).page(params[:page]).per(10)
	      
	    end 


	end

	def too_many_requests

		render "_toomanyrequests"

		
	end





end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tweeted Jobs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>



</head>
<body>

<div class="container">
  <div class="row">

  <div class="about col-md-3">
    <h5>Built as a personal proof of concept. This app queries the Twitter REST API v1.1. Made by <%= link_to "James Robinson", "http://www.jamesarobinson.me", target: "_blank"%>.  </h5>
  </div> 
  <div class="head col-md-9 ">
    <h1>Tweeted Tech Jobs - London</h1>
  </div>  
  </div>
</div>  

<div class="container">

  <div class="content row">



      <div id= "left" class="col-md-3">
        <h4>Popular Searches</h4>

          <ul class="nav nav-pills nav-stacked" role="tablist">
            

            <li role="presentation"><%= link_to "Ruby on Rails", tweets_path(search: "Ruby on Rails") %></li>
            <li role="presentation"><%= link_to "Ruby", tweets_path(search: "Ruby") %></li>
            <li role="presentation"><%= link_to "Python", tweets_path(search: "Python") %></li>
            <li role="presentation"><%= link_to "PHP", tweets_path(search: "PHP") %></li>
            <li role="presentation"><%= link_to "Java", tweets_path(search: "Java") %></li>
            <li role="presentation"><%= link_to "C#", tweets_path(search: "C#") %></li>
            <li role="presentation"><%= link_to "Perl", tweets_path(search: "Perl") %></li>
            <li role="presentation"><%= link_to "Django", tweets_path(search: "Django") %></li>
            <li role="presentation"><%= link_to "NodeJS", tweets_path(search: "NodeJS") %></li>
            <li role="presentation"><%= link_to "EmberJS", tweets_path(search: "EmberJS") %></li>
            <li role="presentation"><%= link_to "HTML & CSS", tweets_path(search: "HTML & CSS") %></li>
            <li role="presentation"><%= link_to "JavaScript", tweets_path(search: "JavaScript") %></li>
            <li role="presentation"><%= link_to "jQuery", tweets_path(search: "jQuery") %></li>
            <li role="presentation"><%= link_to "iOS", tweets_path(search: "iOS") %></li>
            <li role="presentation"><%= link_to "Android", tweets_path(search: "Android") %></li>
            <li role="presentation"><%= link_to "UX/UI", tweets_path(search: "UX/UI") %></li>
            
          </ul>


    


    </div>  


      <div id="right" class="col-md-9">

    	  <%= yield %>


      </div>


  </div>



</div> 
  
  


<script async="" src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
</body>
</html>

app/views/tweets/_toomanyrequests.html.erb
<div class="limit">
<h4>As good as the Twitter API is, it limits the number of queries that can me made in an hour. Unfortunately, we've reached that limit but if you refresh the page in about 15 minutes we should be back up and running!</h4>
</div>

app/views/tweets/index.html.erb
<form action= "<%= tweets_path %>" method="get" %>

	<div class="form-group">

		<%= text_field_tag :search, params[:search], placeholder: "Enter job search term", class: "form-control"  %>

	</div>	

</form>





  <div id="container">

  <% if @tweet_id.empty? %>

  <div class="no-results">
    <h4>Oops, there aren't any results for that search in London. Try another.</h4>
  </div>

  <% else %>
    <% @tweet_id.each do |tweet| %>

    	<div class="item col-md-4">
    	    <%= raw(twitter_client.oembed(tweet, omit_script: true).html) %>
    	</div>

    <%end%>

  <% end %>  
  </div>

    <div class="row">



  <div class="page-button col-md-9 col-md-offset-1">
      <%= paginate @tweet_id, :window => 1 %>
    </div>
  </div>





 